// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbSense.Migrations
{
    [DbContext(typeof(AbSenseDBcontext))]
    [Migration("20260518162726_FixRelationships")]
    partial class FixRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbSense.Models.HolidayBalance", b =>
                {
                    b.Property<int>("HolidayBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayBalanceId"));

                    b.Property<int>("RemainingLeaves")
                        .HasColumnType("int");

                    b.Property<int>("StaffInfoId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAllowance")
                        .HasColumnType("int");

                    b.Property<int>("UsedLeaves")
                        .HasColumnType("int");

                    b.HasKey("HolidayBalanceId");

                    b.HasIndex("StaffInfoId")
                        .IsUnique();

                    b.ToTable("HolidayBalance", (string)null);
                });

            modelBuilder.Entity("AbSense.Models.HolidayInfo", b =>
                {
                    b.Property<int>("HolidayInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayInfoId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByStaffInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveType")
                        .HasColumnType("int");

                    b.Property<string>("ManagerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HolidayInfoId");

                    b.HasIndex("StaffInfoId");

                    b.ToTable("HolidayInfo", (string)null);
                });

            modelBuilder.Entity("AbSense.Models.StaffInfo", b =>
                {
                    b.Property<int>("StaffInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffInfoId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffRole")
                        .HasColumnType("int");

                    b.Property<int>("StaffType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffInfoId");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("AbSense.Models.HolidayBalance", b =>
                {
                    b.HasOne("AbSense.Models.StaffInfo", "StaffInfo")
                        .WithOne("HolidayBalance")
                        .HasForeignKey("AbSense.Models.HolidayBalance", "StaffInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffInfo");
                });

            modelBuilder.Entity("AbSense.Models.HolidayInfo", b =>
                {
                    b.HasOne("AbSense.Models.StaffInfo", "StaffInfo")
                        .WithMany("HolidayInfos")
                        .HasForeignKey("StaffInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffInfo");
                });

            modelBuilder.Entity("AbSense.Models.StaffInfo", b =>
                {
                    b.Navigation("HolidayBalance")
                        .IsRequired();

                    b.Navigation("HolidayInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
